name: Login in Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-delete-vm:
    runs-on: ubuntu-latest

    steps:
    # Fazer login no Azure usando OIDC
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

