name: Create and Delete Azure VM

on:
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  create-delete-vm:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório (se necessário)
    - name: Checkout repository
      uses: actions/checkout@v3

    # Fazer login com a entidade de serviço
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Criar a máquina virtual
    - name: Create Virtual Machine
      run: |
        az group create --name myResourceGroup --location eastus
        az vm create \
          --resource-group myResourceGroup \
          --name myVM \
          --image UbuntuLTS \
          --admin-username azureuser \
          --generate-ssh-keys

    # Aguardar 30 segundos
    - name: Wait 30 seconds
      run: sleep 30

    # Excluir a máquina virtual
    - name: Delete Virtual Machine
      run: |
        az vm delete --name myVM --resource-group myResourceGroup --yes --no-wait
        az group delete --name myResourceGroup --yes --no-wait
